"""What both sides of funduq agree the bytes are."""

CONTRACT_REVISION = 13
"""Which revision of funduq's contract this package implements."""

from funduq_contract.chain import (
    DispatchTarget,
    Hop,
    ChainResult,
    InvalidChain,
    dispatch_hop,
    extend_chain,
    hop_hash,
    new_chain,
    sign_hop,
    verify_chain,
)
from funduq_contract.payloads import (
    cancel_payload,
    view_payload,
    delegation_payload,
    funduq_connect_payload,
    kyok_call_payload,
    provider_connect_payload,
    resolve_payload,
)
from funduq_contract.shapes import (
    Ack,
    Cancel,
    Chunk,
    Complete,
    CompletionBody,
    CompletionEnd,
    CompletionFailed,
    Connect,
    ConnectErr,
    ConnectOk,
    DeliveredCompletion,
    DeliveredRun,
    Offer,
    Refusal,
    Registration,
    Shape,
    Verdict,
)
from funduq_contract.signatures import (
    FINGERPRINT_HEX_LENGTH,
    is_fingerprint,
    new_nonce,
    provider_fingerprint,
    verify_signature,
)

__all__ = [
    "Ack",
    "CONTRACT_REVISION",
    "Cancel",
    "Chunk",
    "Complete",
    "CompletionBody",
    "CompletionEnd",
    "CompletionFailed",
    "Connect",
    "ConnectErr",
    "ConnectOk",
    "DeliveredCompletion",
    "DeliveredRun",
    "Offer",
    "Refusal",
    "Registration",
    "Shape",
    "Verdict",
    "FINGERPRINT_HEX_LENGTH",
    "ChainResult",
    "DispatchTarget",
    "Hop",
    "InvalidChain",
    "cancel_payload",
    "view_payload",
    "delegation_payload",
    "dispatch_hop",
    "extend_chain",
    "funduq_connect_payload",
    "hop_hash",
    "is_fingerprint",
    "kyok_call_payload",
    "new_chain",
    "new_nonce",
    "provider_connect_payload",
    "provider_fingerprint",
    "resolve_payload",
    "sign_hop",
    "verify_chain",
    "verify_signature",
]
